### ISSUE TITLE
Tesla Business Account result in HTTP response status code 429: Too Many Requests since 2023.38.6

### ISSUE THREAD

**Issue by coreGreenberet** [teslamate-org/teslamate#3422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After the changes on https://github.com/teslamate-org/teslamate/issues/3393 teslamate is getting it's updates again, but the new "live update" feature from 2023.38 is not implemented yet. Therefore Teslamate isn't receiving the correct positions and states.

![grafik](https://github.com/teslamate-org/teslamate/assets/3853374/0b75b80f-1de5-4d32-9e40-8803f5d81e18)

As you can see in the data the car was online for a long time, but only driven shortly.

In reality it was like: 15:07 -> drivining 15:10 -> 15:20 driving -> 15:50 -> 16:20 driving -> 16:35 charging

### Expected Behavior

Teslamate should subscribe to the new live data feature and save the data correctly again.

### Steps To Reproduce

Just run teslamate with a car on 2023.38

### Relevant log output

```shell
2023-11-13 15:56:18.954 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9197.667 ms)
2023-11-13 15:56:18.954 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 15:56:18.954 car_id=1 [error] Error / :unknown
2023-11-13 15:56:33.810 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:56:34.830 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:56:38.196 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:56:40.833 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:02.182 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:03.492 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:05.223 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:05.723 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:06.473 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:06.983 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:07.493 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:08.253 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:08.853 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:09.253 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:09.328 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
2023-11-13 15:57:10.054 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:11.153 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:11.323 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:12.523 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:13.283 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:13.675 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9101.870 ms)
2023-11-13 15:57:13.675 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 15:57:13.675 car_id=1 [error] Error / :unknown
2023-11-13 15:57:29.485 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:35.895 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:47.482 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:57:49.592 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:30.927 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:37.266 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:41.887 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:48.213 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:52.835 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:57.375 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:58.905 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:58:59.406 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:00.018 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:00.415 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:01.465 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:02.566 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:03.165 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:03.466 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:04.685 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:05.684 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:06.194 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:06.714 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:07.454 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:07.501 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9095.298 ms)
2023-11-13 15:59:07.502 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 15:59:07.502 car_id=1 [error] Error / :unknown
2023-11-13 15:59:21.770 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:24.780 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:36.793 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:40.313 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:45.693 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:46.495 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:52.374 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:55.304 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:56.324 car_id=1 [info] Fetch already in progress ...
2023-11-13 15:59:59.090 car_id=1 [info] Fetch already in progress ...
2023-11-13 16:00:06.324 car_id=1 [info] Fetch already in progress ...
2023-11-13 16:00:15.191 car_id=1 [info] Fetch already in progress ...
2023-11-13 16:00:17.990 car_id=1 [info] Fetch already in progress ...
2023-11-13 16:00:20.712 car_id=1 [info] Fetch already in progress ...
2023-11-13 16:00:35.136 car_id=1 [info] Fetch already in progress ...
2023-11-13 16:00:49.309 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (221.773 ms)
2023-11-13 16:00:49.778 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (218.939 ms)
2023-11-13 16:00:49.884 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1699887647, heading: 81, latitude: 48.XXXXX, longitude: 16.XXXXX, native_latitude: 48.XXXXX, native_location_supported: 1, native_longitude: 16.XXX, native_type: "wgs", power: 2, shift_state: "P", speed: 0, timestamp: 1699887648698}
2023-11-13 16:00:49.884 car_id=1 [info] Driving / Ended / 18 km – 14 min
2023-11-13 16:00:49.885 car_id=1 [info] Start / :online
2023-11-13 16:03:30.586 car_id=1 [info] Received stream data: :inactive
2023-11-13 16:04:09.335 [notice]     :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}
2023-11-13 16:05:23.487 car_id=1 [info] Suspending logging
2023-11-13 16:35:23.970 car_id=1 [info] Vehicle is still online. Falling asleep for: 33 min
2023-11-13 16:35:23.970 car_id=1 [warning] User present ...
2023-11-13 16:35:24.086 car_id=1 [warning] Received stale stream data: %TeslaApi.Stream.Data{time: ~U[2023-11-13 15:35:23.740Z], speed: nil, odometer: 0.0, soc: 2, elevation: nil, est_heading: nil, est_lat: 112.0, est_lng: 48.XXXX, power: nil, shift_state: "48.XXXXX", range: nil, est_range: 112, heading: nil}
2023-11-13 16:35:39.318 car_id=1 [info] Vehicle is still online. Falling asleep for: 
2023-11-13 16:35:54.724 car_id=1 [info] Vehicle is still online. Falling asleep for: 
2023-11-13 16:36:10.071 car_id=1 [info] Vehicle is still online. Falling asleep for: 
2023-11-13 16:36:10.617 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (543.354 ms)
2023-11-13 16:36:11.326 car_id=1 [info] Charging / SOC: 80% / Daheim
2023-11-13 16:36:11.326 car_id=1 [info] Disconnecting ...
2023-11-13 16:42:30.309 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9105.070 ms)
2023-11-13 16:42:30.310 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 16:42:30.310 car_id=1 [error] Error / :unknown
2023-11-13 16:56:05.493 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9096.734 ms)
2023-11-13 16:56:05.493 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 16:56:05.493 car_id=1 [error] Error / :unknown
2023-11-13 16:56:29.594 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9100.165 ms)
2023-11-13 16:56:29.595 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 16:56:29.595 car_id=1 [error] Error / :unknown
2023-11-13 16:59:15.962 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<car_id>/vehicle_data -> 408 (9093.049 ms)
2023-11-13 16:59:15.963 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-13 16:59:15.963 car_id=1 [error] Error / :unknown
2023-11-13 17:10:10.187 [info] GET /
2023-11-13 17:10:10.207 [info] Sent 200 in 19ms
2023-11-13 17:10:12.029 [info] GET /settings
2023-11-13 17:10:12.039 [info] Sent 200 in 10ms
```

### Additional data

```
[warning] Received stale stream data: %TeslaApi.Stream.Data{time: ~U[2023-11-13 15:35:23.740Z], speed: nil, odometer: 0.0, soc: 2, elevation: nil, est_heading: nil, est_lat: 112.0, est_lng: 48.XXXX, power: nil, shift_state: "48.XXXXX", range: nil, est_range: 112, heading: nil}
```
also it looks like this data stream is value shifted by 1 parameter

I'm running it via the HomeAssistant Addon

### Type of installation

Manual

### Version

1.27.4

**Comment by SylvainGa** [comment]
Directly from Teslamate Grafana page, I'm not seeing that behavior. A drive this morning was correctly recorded (including the path taken on the map) and the State dashboard also had the correct information.

**Comment by SylvainGa** [comment]
Hi, I'm not seeing this behavior from the Grafana page. A drive this morning was correctly recorded, including the path on the map and the State dashboard was also correct. I'm running concurrently the 1.28.0-dev version on my Windows laptop and 1.27.4 on my Raspberry Pie and both shows the same thing.

**Comment by mhumora** [comment]
I had this issue on 1.27.3.

Updating to 1.27.4 resolved the issue.

**Comment by SylvainGa** [comment]
> I had this issue on 1.27.3.
> 
> Updating to 1.27.4 resolved the issue.
> 

He said he's already on 1.27.4

**Comment by federicotravaini** [comment]
I am experiencing the same error.
All 3 cars are on a business account.

```
2023-11-13 18:23:22.883 [info] Starting logger for 'car1'
2023-11-13 18:23:22.885 [info] Starting logger for 'car2'
2023-11-13 18:23:22.887 [info] Starting logger for 'car3'
2023-11-13 18:23:22.940 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car1id-> 429 (49.622 ms)
2023-11-13 18:23:22.940 [warning] TeslaApi.Error / "Retry later\n"
2023-11-13 18:23:22.941 car_id=3 [error] Error / :unknown
2023-11-13 18:23:22.943 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car2id-> 429 (52.870 ms)
2023-11-13 18:23:22.943 [warning] TeslaApi.Error / "Retry later\n"
2023-11-13 18:23:22.943 car_id=1 [error] Error / :unknown
2023-11-13 18:23:22.947 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car3id-> 429 (55.595 ms)
2023-11-13 18:23:22.947 [warning] TeslaApi.Error / "Retry later\n"
2023-11-13 18:23:22.947 car_id=2 [error] Error / :unknown
2023-11-13 18:23:53.003 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car1id-> 429 (53.704 ms)
2023-11-13 18:23:53.003 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car2id-> 429 (61.000 ms)
2023-11-13 18:23:53.003 [warning] TeslaApi.Error / "Retry later\n"
2023-11-13 18:23:53.003 [warning] TeslaApi.Error / "Retry later\n"
2023-11-13 18:23:53.003 car_id=3 [error] Error / :unknown
2023-11-13 18:23:53.003 car_id=2 [error] Error / :unknown
2023-11-13 18:23:53.006 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car3id-> 429 (62.097 ms)
2023-11-13 18:23:53.006 [warning] TeslaApi.Error / "Retry later\n"
2023-11-13 18:23:53.007 car_id=1 [error] Error / :unknown
```

**Comment by federicotravaini** [comment]
adding more logs

```
2023-11-13 18:28:06.904 [error] GenStateMachine :"3" terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{date: ~U[2023-11-13 18:28:06.778000Z], speed: 0, power: 0, odometer: 8924.772423, battery_heater: false, driver_temp_setting: Decimal.new("23.5"), fan_status: 0, inside_temp: Decimal.new("18.0"), is_climate_on: false, is_front_defroster_on: false, is_rear_defroster_on: false, outside_temp: Decimal.new("13.5"), passenger_temp_setting: Decimal.new("23.5"), tpms_pressure_fl: Decimal.new("2.825"), tpms_pressure_fr: Decimal.new("2.825"), tpms_pressure_rl: Decimal.new("2.725"), tpms_pressure_rr: Decimal.new("2.85"), battery_heater_on: false, battery_level: 72, usable_battery_level: 72, ideal_battery_range_km: Decimal.new("445.1"), rated_battery_range_km: Decimal.new("445.1"), est_battery_range_km: Decimal.new("406.58")}, errors: [latitude: {"can't be blank", [validation: :required]}, longitude: {"can't be blank", [validation: :required]}], data: #TeslaMate.Log.Position<>, valid?: false>}
    (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:721: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
    (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
    (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
2023-11-13 18:28:06.974 car_id=1 [info] Start / :online
2023-11-13 18:28:06.977 [error] GenStateMachine :"1" terminating
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{date: ~U[2023-11-13 18:28:06.936000Z], power: 0, odometer: 81187.104988, battery_heater: false, battery_heater_no_power: false, driver_temp_setting: Decimal.new("22.0"), fan_status: 0, inside_temp: Decimal.new("21.1"), is_climate_on: false, is_front_defroster_on: false, is_rear_defroster_on: false, outside_temp: Decimal.new("13.0"), passenger_temp_setting: Decimal.new("22.0"), tpms_pressure_fl: Decimal.new("2.875"), tpms_pressure_fr: Decimal.new("2.875"), tpms_pressure_rl: Decimal.new("2.9"), tpms_pressure_rr: Decimal.new("2.85"), battery_heater_on: false, battery_level: 60, usable_battery_level: 60, ideal_battery_range_km: Decimal.new("1607.73"), rated_battery_range_km: Decimal.new("306.15"), est_battery_range_km: Decimal.new("296.89")}, errors: [latitude: {"can't be blank", [validation: :required]}, longitude: {"can't be blank", [validation: :required]}], data: #TeslaMate.Log.Position<>, valid?: false>}
    (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:721: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
    (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
    (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
    (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by dquach93** [comment]
@federicotravaini - are you on 1.27.4?

**Comment by jlestel** [comment]
> I am experiencing the same error. All 3 cars are on a business account.
> 
> ```
> 2023-11-13 18:23:22.883 [info] Starting logger for 'car1'
> 2023-11-13 18:23:22.885 [info] Starting logger for 'car2'
> 2023-11-13 18:23:22.887 [info] Starting logger for 'car3'
> 2023-11-13 18:23:22.940 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car1id-> 429 (49.622 ms)
> 2023-11-13 18:23:22.940 [warning] TeslaApi.Error / "Retry later\n"
> 2023-11-13 18:23:22.941 car_id=3 [error] Error / :unknown
> 2023-11-13 18:23:22.943 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car2id-> 429 (52.870 ms)
> 2023-11-13 18:23:22.943 [warning] TeslaApi.Error / "Retry later\n"
> 2023-11-13 18:23:22.943 car_id=1 [error] Error / :unknown
> 2023-11-13 18:23:22.947 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car3id-> 429 (55.595 ms)
> 2023-11-13 18:23:22.947 [warning] TeslaApi.Error / "Retry later\n"
> 2023-11-13 18:23:22.947 car_id=2 [error] Error / :unknown
> 2023-11-13 18:23:53.003 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car1id-> 429 (53.704 ms)
> 2023-11-13 18:23:53.003 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car2id-> 429 (61.000 ms)
> 2023-11-13 18:23:53.003 [warning] TeslaApi.Error / "Retry later\n"
> 2023-11-13 18:23:53.003 [warning] TeslaApi.Error / "Retry later\n"
> 2023-11-13 18:23:53.003 car_id=3 [error] Error / :unknown
> 2023-11-13 18:23:53.003 car_id=2 [error] Error / :unknown
> 2023-11-13 18:23:53.006 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/car3id-> 429 (62.097 ms)
> 2023-11-13 18:23:53.006 [warning] TeslaApi.Error / "Retry later\n"
> 2023-11-13 18:23:53.007 car_id=1 [error] Error / :unknown
> ```

The HTTP response status code 429 Too Many Requests indicates that the user has sent too many requests in a given time.

**Comment by tallmikey** [comment]
It seems related to the new Tesla firmware 2023.38. I upgraded my tesla MY to 2023.38 at Sunday 2am then haven't be able to get any live data after the Tesla firmware upgrade.

**Comment by coreGreenberet** [comment]
Yesterday I was driving a little bit more, but I'm missing small drives.
I was on a non Tesla Charger (I know shame on me) and it wasn't really working. So I did a few turns and tried different outlets.
-> Park -> Drive for a few seconds -> repark and repeat that.

None of these were recorded. The charging itself wasn't recorded at all and the drive has started "later" as you can see in the image with the straight line

![grafik](https://github.com/teslamate-org/teslamate/assets/3853374/8f063600-a1e4-4e66-b907-d62ebd0f1a5c)

**Comment by Orbedk** [comment]
I see the same behavior after updating to 2023.38.6 - no live date available. And the same error in log files

**Comment by followsound** [comment]
Same here on `1.27.3` or `1.27.4` with Tesla on `2023.38.6`

**Comment by DrMichael** [comment]
Hmmm, http error 429 means "too many requests"...

**Comment by alsFC** [comment]
Had the same behavior after updating the MY to 2023.38.6 with TM 1.27.3. After TM upgrading to 1.27.4 I still got old values until I woke up the car. No it seems to be working again.

**Comment by Orbedk** [comment]
> I see the same behavior after updating to 2023.38.6 - no live data available. And the same error in log files

I just did a recreate container through portainer with the option to pull new image only on the TM-container - this seems to have solved my issue, even though it didn’t update anything as far as I know.

Guess a docker-pull and docker up -d will also solve this.

**Comment by SylvainGa** [comment]
> > I see the same behavior after updating to 2023.38.6 - no live data available. And the same error in log files
> 
> I just did a recreate container through portainer with the option to pull new image only on the TM-container - this seems to have solved my issue, even though it didn’t update anything as far as I know, was already on 1.27.4
> 
> Guess a docker-pull and docker up -d will also solve this.
> 
> 

Well if you're pulling :latest, then yes, since the latest has this issue fixed. It's the recommended way to update. Until two days ago however, the 'latest' was still 1.27.3 so you had to pull from a different docker image (1.28-beta) to have it fixed.

**Comment by brianmay** [comment]
On the topic of the 429 responses, I believe Tesla do rate limit now. Yuck. See https://developer.tesla.com/docs/fleet-api#membership-tiers

I suspect this might affect teslamate:

> Device data limits
>
> 1 API request / car / 5 min
> And
> 1M API requests / day

Also see FAQ - https://developer.tesla.com/docs/fleet-api#faq:

> Why do some calls return a 429?
>
> This means the account has reached the request rate limit for the endpoint. Check the 'Retry-After' request header (in seconds) to determine when to make the next request. See [more information on response codes](https://developer.tesla.com/docs/fleet-api#response-codes). 

Reading between the lines, it is not an attempt to protect against DDOS, rather it is justification to charge $$$ for better limits.

**Comment by brianmay** [comment]
> Check the 'Retry-After' request header (in seconds)

This documentation is bad. I have no idea what they are talking about. Possible the HTTP headers of the 429 response? Or maybe the JSON body of the response?

**Comment by jlestel** [comment]
> > Check the 'Retry-After' request header (in seconds)
> 
> This documentation is bad. I have no idea what they are talking about. Possible the HTTP headers of the 429 response? Or maybe the JSON body of the response?

This is not bad : It's in the [HTTP header of the call response which results in 429](https://medium.com/@BearerSH/error-429-too-many-requests-youve-been-rate-limited-a4d41e94b8e6).

We find in the Retry-After value the time to wait before making a new call. I assume that each new call increases this value.

The Elixir code should take this value into account before making new calls.

**Comment by ngardiner** [comment]
The documentation refers to the Tesla fleet-api api interface which is different to the owner api. It requires the use of a developer key as documented at the top of the page and targets the specific fleet-api.xx.tesla.com interface.

That's not to say that Tesla haven't introduced rate limiting on the owner-api, but there's no current reference in the TeslaMate source to the fleet-api endpoint.

**Comment by jlestel** [comment]
The underlying logic remains the same. 
This is a 429 error: there is a header in the response which should indicate the time to wait.

**Comment by brianmay** [comment]
The reports of 429 come from a business account. So maybe doesn't affect personal cars. For now...

But regardless, it sounds like we should at the very least try to catch the 429 and display the `Retry-After` header. To ensure it really does contain what it is suppose to contain.

**Comment by aklira** [comment]
I had the same problem with Tesla software upgrade 2023.38.6 But updating to the latest version of Teslamate solved the problem.

**Comment by aviateur17** [comment]
I had same issue for my personal car after it updated 2 days ago.  I updated my teslamate image via portainer to the latest and it was fixed.   I'm pretty sure while troubleshooting the issue I did see 429 error messages for my personal car so it would be nice to update the Elixor code or whatever to react to those throttling messages.

**Comment by SylvainGa** [comment]
I think the 429s for me were caused by the code querying the servers in rapid succession when the data was invalid due to the API change. Tesla probably saw that burst of requests and issued 429s in response.

**Comment by NickWhitNTES** [comment]
I had the same initial issue too, but it has since been working fine.  Business account also

**Comment by coreGreenberet** [comment]
I don't see the 429 error messages anymore and the data looks like it got "okay" again. I'm still not 100% sure yet, but it's definitely better.

I don't know if it is normal or if the error was in the past too, but at the moment I'm also seeing some timeouts from the api calls.

```
2023-11-16 07:39:02.918 car_id=1 [info] Driving / Start
2023-11-16 08:19:26.637 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9094.286 ms)
2023-11-16 08:19:26.637 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-16 08:19:26.637 car_id=1 [error] Error / :unknown
2023-11-16 08:19:45.732 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9093.415 ms)
2023-11-16 08:19:45.732 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-16 08:19:45.732 car_id=1 [error] Error / :unknown
2023-11-16 08:20:04.831 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9097.637 ms)
2023-11-16 08:20:04.832 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-16 08:20:04.832 car_id=1 [error] Error / :unknown
2023-11-16 08:20:20.059 car_id=1 [info] Received stream data: :inactive
2023-11-16 08:20:23.944 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9111.234 ms)
2023-11-16 08:20:23.944 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2023-11-16 08:20:23.944 car_id=1 [error] Error / :unknown
2023-11-16 08:20:28.321 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
```

I'm also really sure, that my fuse hasn't blown yet =D

**Comment by alsFC** [comment]
> I don't see the 429 error messages anymore and the data looks like it got "okay" again. I'm still not 100% sure yet, but it's definitely better.
> 
> I don't know if it is normal or if the error was in the past too, but at the moment I'm also seeing some timeouts from the api calls.
> 
> ```
> 2023-11-16 07:39:02.918 car_id=1 [info] Driving / Start
> 2023-11-16 08:19:26.637 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9094.286 ms)
> 2023-11-16 08:19:26.637 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 2023-11-16 08:19:26.637 car_id=1 [error] Error / :unknown
> 2023-11-16 08:19:45.732 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9093.415 ms)
> 2023-11-16 08:19:45.732 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 2023-11-16 08:19:45.732 car_id=1 [error] Error / :unknown
> 2023-11-16 08:20:04.831 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9097.637 ms)
> 2023-11-16 08:20:04.832 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 2023-11-16 08:20:04.832 car_id=1 [error] Error / :unknown
> 2023-11-16 08:20:20.059 car_id=1 [info] Received stream data: :inactive
> 2023-11-16 08:20:23.944 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/<CAR>/vehicle_data -> 408 (9111.234 ms)
> 2023-11-16 08:20:23.944 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 2023-11-16 08:20:23.944 car_id=1 [error] Error / :unknown
> 2023-11-16 08:20:28.321 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
> ```
> 
> I'm also really sure, that my fuse hasn't blown yet =D

I can also see those 408 codes in my logs! But nevertheless I'm retrieving data..
My account is a business account.

**Comment by DrMichael** [comment]
Error 408 is Request Timeout. That happens once in a while.

**Comment by brianmay** [comment]
I am guessing that might happen when the Tesla Endpoint cannot talk to the car for some reason (e.g. car lost mobile reception).

**Comment by DrMichael** [comment]
Probably rather, that the Tesla server(s) were not responding...

**Comment by SylvainGa** [comment]
408 errors are to be expected when the car is asleep as it won't respond to getting vehicle data. In my apps (Garmin's Tesla-Link and Crystal-Tesla - also on GitHub), I handle 408 the following way:

When you ask the Tesla servers for a list of vehicles, you'll get the state of the car, and when it's online, you can query for its data. If you get 408 then, it's mostly due to communication errors (ie, flaky cellular or wi-fi coverage). But, as the car falls asleep, there is a period of time that the car won't respond and the vehicle list will still return "online". You'll start to get 408 then.

So my apps query for the car's data and if I get 408, I check Tesla's server for its state and if "asleep", I state so, otherwise I show that 408 error. Teslamate probably does something similar.

**Comment by b3ko91** [comment]
Same issue for me after vehicule upgrade. Now Tesla limite API access. :-(

**Comment by brianmay** [comment]
Which one, 408, or 429?

408 is OK:

> If the vehicle is not "online" when a request is made. 

429 not OK:

> Account or server is rate limited. This happens when too many requests are made by an account.
• Check the 'Retry-After' request header (in seconds) to determine when to make the next request.

Source: https://developer.tesla.com/docs/fleet-api#response-codes

**Comment by b3ko91** [comment]
> Which one, 408, or 429?
> 
> 408 is OK:
> 
> > If the vehicle is not "online" when a request is made.
> 
> 429 not OK:
> 
> > Account or server is rate limited. This happens when too many requests are made by an account.
> > • Check the 'Retry-After' request header (in seconds) to determine when to make the next request.
> 
> Source: https://developer.tesla.com/docs/fleet-api#response-codes

429 😕

**Comment by JakobLichterfeld** [comment]
Linking #3451

**Comment by DrMichael** [comment]
Do we need to put in a delay?
Does this only affect people with more than one car?

**Comment by brianmay** [comment]
Supposedly the rate limits are per car, so having multiple cars shouldn't matter.

No idea if we need this, so far for my personal use I am not seeing these 429 responses.

**Comment by JakobLichterfeld** [comment]
This is only related to business accounts, who violated TOS when using streaming api I guess.

**Comment by SylvainGa** [comment]
> This is only related to business accounts, who violated TOS when using streaming api I guess.

I didn't think so. I also received 429 before I upgraded to 1.27.4 (or 1.28-beta). My assumption is that there is (was?) an issue in the code when invalid data is received (like the missing latitude/longitude) and the code pounds the Tesla's server which in return sends the 429 error.

**Comment by JakobLichterfeld** [comment]
Nothing related to TeslaMate 1.27.4.
Business accounts are probalbly not allowed to use streaming api since Tesla Firmware update including the new fleet api.

**Comment by coreGreenberet** [comment]
I think we can close this issue

**Comment by b3ko91** [comment]
For me all is right. Thanks to all

**Comment by brianmay** [comment]
I started seeing this error on my car last night. But not from TeslaMate, my own software. My car tried to send it a request to charge, and it responded with 429 every single time - even the first attempt.

Will try to add more debugging.

**Comment by jlestel** [comment]
> I started seeing this error on my car last night. But not from TeslaMate, my own software. My car tried to send it a request to charge, and it responded with 429 every single time - even the first attempt.
> 
> Will try to add more debugging.

When the response code is 429, it would be great to check the 'Retry-After' request header (in seconds) to determine when to make the next request.

**Comment by brianmay** [comment]
Agreed.

This may require restructuring the code. Not sure if we can easily feed the retry time back from the error header. But I haven't really looked either.

Testing might also be hard, due the the infrequent nature of this happening.

Have implemented in my own code (a) logging of all request headers, and (b) attempt to parse the "Retry-After" header and do something sensible with it. Testing might be the hard part :-)
